from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 222)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.from_1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.from_1.setMinimum(1)
        self.from_1.setObjectName("from_1")
        self.verticalLayout_3.addWidget(self.from_1)
        self.from_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.from_2.setMinimum(1)
        self.from_2.setObjectName("from_2")
        self.verticalLayout_3.addWidget(self.from_2)
        self.from_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.from_3.setMinimum(1)
        self.from_3.setObjectName("from_3")
        self.verticalLayout_3.addWidget(self.from_3)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.to_1 = QtWidgets.QSpinBox(self.groupBox_3)
        self.to_1.setProperty("value", 10)
        self.to_1.setObjectName("to_1")
        self.verticalLayout_4.addWidget(self.to_1)
        self.to_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.to_2.setProperty("value", 10)
        self.to_2.setObjectName("to_2")
        self.verticalLayout_4.addWidget(self.to_2)
        self.to_3 = QtWidgets.QSpinBox(self.groupBox_3)
        self.to_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.to_3.setProperty("value", 10)
        self.to_3.setObjectName("to_3")
        self.verticalLayout_4.addWidget(self.to_3)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.res_1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.res_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_1.setReadOnly(True)
        self.res_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.res_1.setObjectName("res_1")
        self.verticalLayout_5.addWidget(self.res_1)
        self.res_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.res_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_2.setReadOnly(True)
        self.res_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.res_2.setObjectName("res_2")
        self.verticalLayout_5.addWidget(self.res_2)
        self.res_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.res_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_3.setReadOnly(True)
        self.res_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.res_3.setObjectName("res_3")
        self.verticalLayout_5.addWidget(self.res_3)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.st_1 = QtWidgets.QSpinBox(self.groupBox_6)
        self.st_1.setProperty("value", 1)
        self.st_1.setObjectName("st_1")
        self.gridLayout.addWidget(self.st_1, 0, 0, 1, 1)
        self.st_2 = QtWidgets.QSpinBox(self.groupBox_6)
        self.st_2.setProperty("value", 1)
        self.st_2.setObjectName("st_2")
        self.gridLayout.addWidget(self.st_2, 1, 0, 1, 1)
        self.st_3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.st_3.setProperty("value", 1)
        self.st_3.setObjectName("st_3")
        self.gridLayout.addWidget(self.st_3, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.triggered)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Brute Force"))
        self.groupBox.setTitle(_translate("Form", "Степені"))
        self.groupBox_5.setTitle(_translate("Form", "Вектор"))
        self.label.setText(_translate("Form", "X1"))
        self.label_2.setText(_translate("Form", "X2"))
        self.label_3.setText(_translate("Form", "X3"))
        self.groupBox_2.setTitle(_translate("Form", "Від"))
        self.groupBox_3.setTitle(_translate("Form", "До"))
        self.groupBox_4.setTitle(_translate("Form", "Результат"))
        self.groupBox_6.setTitle(_translate("Form", "Кроки"))
        self.pushButton.setText(_translate("Form", "Розрахувати"))

